import type { StoreConfigInput } from '@/config/store-config.schema';

export const blankStoreConfig: StoreConfigInput = {
  brand: {
    name: 'New Store',
    logo: '/placeholder-logo.svg',
    logoAlt: 'Store Logo',
    tagline: '',
  },
  seo: {
    title: 'New Store',
    description: 'A new Cuclify store.',
    keywords: [],
    productNotFoundTitle: 'Product Not Found',
    productNotFoundDescription: 'This product is not currently available.',
    viewport: {
      lightThemeColor: '#ffffff',
      darkThemeColor: '#000000',
    },
    language: 'en',
  },
  theme: {
    colors: {
      light: {
        primary: 'oklch(0.205 0 0)',
        primaryForeground: 'oklch(0.985 0 0)',
        secondary: 'oklch(0.96 0.01 80)',
        secondaryForeground: 'oklch(0.205 0 0)',
        background: 'oklch(0.99 0.005 80)',
        foreground: 'oklch(0.145 0 0)',
        muted: 'oklch(0.96 0.01 80)',
        mutedForeground: 'oklch(0.45 0 0)',
        accent: 'oklch(0.65 0.15 45)',
        accentForeground: 'oklch(0.985 0 0)',
        border: 'oklch(0.9 0.01 80)',
        card: 'oklch(1 0 0)',
        cardForeground: 'oklch(0.145 0 0)',
      },
      dark: {
        primary: 'oklch(0.985 0 0)',
        primaryForeground: 'oklch(0.145 0 0)',
        secondary: 'oklch(0.25 0.01 80)',
        secondaryForeground: 'oklch(0.985 0 0)',
        background: 'oklch(0.12 0 0)',
        foreground: 'oklch(0.985 0 0)',
        muted: 'oklch(0.25 0.01 80)',
        mutedForeground: 'oklch(0.65 0 0)',
        accent: 'oklch(0.7 0.15 45)',
        accentForeground: 'oklch(0.145 0 0)',
        border: 'oklch(0.28 0.01 80)',
        card: 'oklch(0.16 0 0)',
        cardForeground: 'oklch(0.985 0 0)',
      },
    },
    typography: {
      fontSans: 'Geist',
      fontSerif: 'Playfair Display',
      fontMono: 'Geist Mono',
      headingWeight: '600',
      bodyWeight: '400',
    },
    spacing: {
      sectionPadding: 'py-16 md:py-24',
      containerMaxWidth: 'max-w-7xl',
      gap: 'gap-8',
    },
    borderRadius: '0.75rem',
  },
  navigation: {
    navbar: {
      links: [],
      showSearch: true,
      searchPlaceholder: 'Search...',
      showCart: true,
      showAuth: true,
    },
  },
  commerce: {
    locale: 'en-US',
    currency: 'USD',
    tax: {
      rate: 0,
    },
    shipping: {
      freeThreshold: 0,
      standardRate: 0,
    },
  },
  catalog: {
    categories: {
      title: 'Categories',
      subtitle: 'No categories yet',
      categories: [],
      columns: 4,
    },
    products: {
      title: 'Products',
      subtitle: 'No products yet',
      productCardLabels: {
        quickAddLabel: 'Add to Cart',
        outOfStockLabel: 'Out of Stock',
      },
      products: [],
      columns: 4,
    },
  },
  pages: {
    home: {
      hero: {
        badge: '',
        headline: 'Start building your store',
        subheadline: 'Your new store is ready for its first pieces.',
        buttons: [],
        alignment: 'center',
      },
      benefits: {
        title: 'Benefits',
        subtitle: 'No benefits yet',
        benefits: [],
        layout: 'grid',
      },
      promo: {
        headline: 'Promo Banner',
        subheadline: 'No promo message yet',
        button: {
          label: 'Shop Now',
          href: '/products',
        },
      },
      testimonials: {
        title: 'Testimonials',
        subtitle: 'No testimonials yet',
        testimonials: [],
        layout: 'grid',
      },
      faq: {
        title: 'FAQ',
        subtitle: 'No questions yet',
        items: [],
      },
      sections: [
        { type: 'hero' },
        { type: 'categoryGrid' },
        { type: 'featuredProducts' },
        { type: 'benefits' },
        { type: 'promoBanner' },
        { type: 'testimonials' },
        { type: 'faq' },
      ],
    },
    products: {
      title: 'All Products',
      subtitle: 'Explore our collection',
      searchPlaceholder: 'Search products...',
      sortOptions: [
        { id: 'featured', label: 'Featured', value: 'featured' },
        { id: 'newest', label: 'Newest', value: 'newest' },
        { id: 'price-asc', label: 'Price: Low to High', value: 'price-asc' },
        { id: 'price-desc', label: 'Price: High to Low', value: 'price-desc' },
      ],
      filterTitle: 'Filters',
      categoryFilterLabel: 'Category',
      priceFilterLabel: 'Price',
      priceRanges: [
        { id: 'all', label: 'All Prices' },
      ],
      noResultsText: 'No products found.',
      resultsPerPage: 12,
      productCardLabels: {
        quickAddLabel: 'Add to Cart',
        outOfStockLabel: 'Out of Stock',
      },
    },
    productDetail: {
      addToCartLabel: 'Add to Cart',
      buyNowLabel: 'Buy Now',
      outOfStockLabel: 'Out of Stock',
      quantityLabel: 'Quantity',
      variantLabel: 'Options',
      descriptionLabel: 'Description',
      detailsLabel: 'Details',
      shippingLabel: 'Shipping',
      returnsLabel: 'Returns',
      breadcrumbs: {
        homeLabel: 'Home',
        productsLabel: 'Products',
      },
      detailsCopyLabels: {
        categoryLabel: 'Category',
        tagsLabel: 'Tags',
        skuLabel: 'SKU',
      },
      shippingCopy: {
        standardShipping: 'Standard shipping available.',
        expressShipping: 'Express shipping available.',
        estimatedDelivery: '3-7 business days.',
      },
      reviewCountLabel: 'reviews',
      saveLabel: 'Save',
      trustBadges: {
        freeShippingLabel: 'Free Shipping',
        easyReturnsLabel: 'Easy Returns',
        securePaymentLabel: 'Secure Payment',
      },
      relatedProductsTitle: 'Recommended',
      productCardLabels: {
        quickAddLabel: 'Add to Cart',
        outOfStockLabel: 'Out of Stock',
      },
    },
    cart: {
      title: 'Cart',
      metadataDescription: 'Your shopping cart.',
      emptyState: {
        title: 'Your cart is empty',
        description: 'Add items to start shopping.',
        buttonLabel: 'Continue Shopping',
        buttonHref: '/products',
      },
      itemCountLabel: {
        singular: 'item',
        plural: 'items',
        suffix: 'in your cart',
      },
      summary: {
        title: 'Summary',
        subtotalLabel: 'Subtotal',
        shippingLabel: 'Shipping',
        shippingValue: 'Calculated at checkout',
        taxLabel: 'Tax',
        totalLabel: 'Total',
      },
      checkoutButton: {
        label: 'Checkout',
        href: '/checkout',
      },
      continueShoppingLink: {
        label: 'Continue Shopping',
        href: '/products',
      },
    },
    checkout: {
      title: 'Checkout',
      metadataDescription: 'Complete your order.',
      steps: [
        { id: 'info', title: 'Info' },
        { id: 'shipping', title: 'Shipping' },
        { id: 'payment', title: 'Payment' },
      ],
      emptyState: {
        title: 'Your cart is empty',
        description: 'Add items before checking out.',
        continueShoppingLabel: 'Continue Shopping',
        continueShoppingHref: '/products',
      },
      customerInfo: {
        title: 'Contact',
        emailLabel: 'Email',
        emailPlaceholder: 'email@example.com',
        phoneLabel: 'Phone',
        phonePlaceholder: 'Phone number',
      },
      shippingInfo: {
        title: 'Shipping',
        firstNameLabel: 'First Name',
        firstNamePlaceholder: '',
        lastNameLabel: 'Last Name',
        lastNamePlaceholder: '',
        addressLabel: 'Address',
        addressPlaceholder: '',
        apartmentLabel: 'Apartment',
        apartmentPlaceholder: '',
        cityLabel: 'City',
        cityPlaceholder: '',
        stateLabel: 'State',
        statePlaceholder: '',
        zipLabel: 'ZIP',
        zipPlaceholder: '',
        countryLabel: 'Country',
        countryPlaceholder: '',
      },
      paymentInfo: {
        title: 'Payment',
        cardNumberLabel: 'Card Number',
        cardNumberPlaceholder: '',
        expiryLabel: 'Expiry',
        expiryPlaceholder: 'MM/YY',
        cvvLabel: 'CVV',
        cvvPlaceholder: '',
        nameOnCardLabel: 'Name on Card',
        nameOnCardPlaceholder: '',
      },
      orderSummary: {
        title: 'Order Summary',
        subtotalLabel: 'Subtotal',
        shippingLabel: 'Shipping',
        taxLabel: 'Tax',
        totalLabel: 'Total',
        freeShippingLabel: 'Free',
      },
      labels: {
        secure: 'Secure',
        back: 'Back',
        continue: 'Continue',
      },
      placeOrderButton: 'Place Order',
      successState: {
        title: 'Thank you!',
        description: 'Order confirmed.',
        orderNumberLabel: 'Order #',
        continueShoppingLabel: 'Continue Shopping',
        continueShoppingHref: '/products',
      },
    },
  },
  footer: {
    brand: {
      name: 'New Store',
      logo: '/placeholder-logo.svg',
      tagline: '',
    },
    linkGroups: [],
    socialLinks: [],
    copyright: '© 2024 New Store. All rights reserved.',
  },
};
