import type { StoreConfig } from '@/types';

export const categories: StoreConfig['categories'] = {
    title: 'Shop by Category',
    subtitle: 'Explore our carefully curated collections',
    categories: [
      {
        id: 'living',
        name: 'Living',
        description: 'Furniture & decor',
        image:
          'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop',
        href: '/category/living',
        productCount: 124,
      },
      {
        id: 'bedroom',
        name: 'Bedroom',
        description: 'Rest & relaxation',
        image:
          'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=600&h=400&fit=crop',
        href: '/category/bedroom',
        productCount: 86,
      },
      {
        id: 'kitchen',
        name: 'Kitchen',
        description: 'Culinary essentials',
        image:
          'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=400&fit=crop',
        href: '/category/kitchen',
        productCount: 98,
      },
      {
        id: 'office',
        name: 'Office',
        description: 'Workspace solutions',
        image:
          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&h=400&fit=crop',
        href: '/category/office',
        productCount: 67,
      },
    ],
    columns: 4,
  };

export const products: StoreConfig['products'] = {
    title: 'Featured Products',
    subtitle: 'Handpicked favorites from our collection',
    viewAllLink: {
      label: 'View all products',
      href: '/products',
    },
    productCardLabels: {
      quickAddLabel: 'Quick Add',
      outOfStockLabel: 'Out of stock',
    },
    products: [
      {
        id: 'prod-1',
        name: 'Minimalist Desk Lamp',
        description: 'Sleek brass and marble table lamp with adjustable head',
        price: 189,
        compareAtPrice: 229,
        currency: 'USD',
        images: [
          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
        ],
        category: 'Lighting',
        tags: ['new', 'bestseller'],
        badge: 'Best Seller',
        rating: 4.9,
        reviewCount: 128,
        inStock: true,
        href: '/product/minimalist-desk-lamp',
        variants: null,
      },
      {
        id: 'prod-2',
        name: 'Ceramic Vase Set',
        description: 'Hand-crafted ceramic vases in neutral tones',
        price: 79,
        compareAtPrice: null,
        currency: 'USD',
        images: [
          'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&h=600&fit=crop',
        ],
        category: 'Decor',
        tags: ['handmade'],
        badge: null,
        rating: 4.7,
        reviewCount: 84,
        inStock: true,
        href: '/product/ceramic-vase-set',
        variants: null,
      },
      {
        id: 'prod-3',
        name: 'Linen Throw Blanket',
        description: 'Premium Belgian linen throw in oatmeal',
        price: 145,
        compareAtPrice: null,
        currency: 'USD',
        images: [
          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
        ],
        category: 'Textiles',
        tags: ['sustainable'],
        badge: 'Eco-Friendly',
        rating: 4.8,
        reviewCount: 96,
        inStock: true,
        href: '/product/linen-throw-blanket',
        variants: null,
      },
      {
        id: 'prod-4',
        name: 'Oak Side Table',
        description: 'Solid white oak side table with rounded edges',
        price: 295,
        compareAtPrice: 350,
        currency: 'USD',
        images: [
          'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=600&h=600&fit=crop',
        ],
        category: 'Furniture',
        tags: ['sale'],
        badge: 'Sale',
        rating: 4.9,
        reviewCount: 52,
        inStock: true,
        href: '/product/oak-side-table',
        variants: null,
      },
      {
        id: 'prod-5',
        name: 'Scented Candle Trio',
        description: 'Soy wax candles in cedar, lavender, and vanilla',
        price: 64,
        compareAtPrice: null,
        currency: 'USD',
        images: [
          'https://images.unsplash.com/photo-1602607434943-0b3a67c03ccc?w=600&h=600&fit=crop',
        ],
        category: 'Home Fragrance',
        tags: null,
        badge: null,
        rating: 4.6,
        reviewCount: 203,
        inStock: true,
        href: '/product/scented-candle-trio',
        variants: null,
      },
      {
        id: 'prod-6',
        name: 'Woven Storage Basket',
        description: 'Handwoven seagrass basket with leather handles',
        price: 58,
        compareAtPrice: null,
        currency: 'USD',
        images: [
          'https://images.unsplash.com/photo-1586105449897-20b5efeb3233?w=600&h=600&fit=crop',
        ],
        category: 'Storage',
        tags: ['handmade', 'sustainable'],
        badge: null,
        rating: 4.5,
        reviewCount: 67,
        inStock: true,
        href: '/product/woven-storage-basket',
        variants: null,
      },
      {
        id: 'prod-7',
        name: 'Marble Bookends',
        description: 'Solid Carrara marble bookend pair',
        price: 125,
        compareAtPrice: null,
        currency: 'USD',
        images: [
          'https://images.unsplash.com/photo-1544457070-4cd773b4d71e?w=600&h=600&fit=crop',
        ],
        category: 'Decor',
        tags: null,
        badge: 'New',
        rating: 4.8,
        reviewCount: 31,
        inStock: true,
        href: '/product/marble-bookends',
        variants: null,
      },
      {
        id: 'prod-8',
        name: 'Velvet Cushion Cover',
        description: 'Luxurious velvet cushion in forest green',
        price: 42,
        compareAtPrice: null,
        currency: 'USD',
        images: [
          'https://images.unsplash.com/photo-1629949009765-3da65ae1678a?w=600&h=600&fit=crop',
        ],
        category: 'Textiles',
        tags: null,
        badge: null,
        rating: 4.7,
        reviewCount: 142,
        inStock: true,
        href: '/product/velvet-cushion-cover',
        variants: null,
      },
    ],
    columns: 4,
  };

